# This workflow uses the following github action to automate
# management of stale issues and prs in this repo:
# https://github.com/marketplace/actions/close-stale-issues

name: Close stale issues and PRs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@cdf15f641adb27a71842045a94023bef6945e3aa # v4.0.0
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 10
          days-before-pr-stale: -1
          days-before-pr-close: -1
          stale-issue-label: auto-triage-stale
          stale-issue-message: 👋 It looks like this issue has been open for 30 days with no activity. We'll mark this as stale for now, and wait 10 days for an update or for further comment before closing this issue out.
          close-issue-message: As this issue has been inactive for more than one month, we will be closing it. Thank you to all the participants! If you would like to raise a related issue, please create a new issue which includes your specific details and references this issue number.
          exempt-issue-labels: auto-triage-skip,bug,discussion,docs,enhancement,security,tests
          exempt-all-milestones: true
          remove-stale-when-updated: true
          enable-statistics: true
          operations-per-run: 60
